### ISSUE TITLE
Create_Sign_Up_Page_UI

### ISSUE THREAD

**Issue by Rontim** [Rontim/JKUAT-CU-App#1]
### **Feature: Sign Up Page (UI Only)**

**Issue:** #Create_Sign_Up_Page_UI

#### **Description:**
We need to create the UI for the sign-up page. This screen will allow new users to input their details for account registration. The UI should be consistent with the overall theme and responsive across various devices.

#### **Requirements:**

1. **Design:**
   - Create a **sign-up form** with the following fields:
     - First Name
     - Last Name
     - Email
     - Password
     - Confirm Password
   - Add a **Sign Up** button at the bottom of the form.
   - Below the form, add a text link for users who already have an account (e.g., "Already have an account? Login").
   - Add options for social signup
   
2. **UI Components:**
   - Use **TextFields** for user input.
   - Ensure the **password fields** hide text using the standard password entry style (obscured).
   - The **Sign Up button** should be styled according to the app's theme.
   - The layout should be responsive and work well on different screen sizes.

3. **Design Consistency:**
   - Follow the same color scheme and typography as the existing `LoginPage` and `WelcomePage`.
   - Ensure proper padding, spacing, and alignment.

4. **Navigation:**
   - Add a placeholder function for the **Sign Up** button (no need to connect it to any logic yet).
   - Ensure that clicking the "Already have an account? Login" link navigates the user to the login screen using GetX's `Get.to()` method (or another method for simple routing).

#### **Acceptance Criteria:**
- The sign-up page UI should have all the required input fields and button.
- The layout should be clean, visually appealing, and responsive on both small and large screens.
- Clicking the "Already have an account?" link should navigate to the login page (without handling any backend logic yet).

#### **Additional Notes:**
- Refer to the existing `LoginPage` for consistency in styling and layout.
- The focus of this issue is purely the UI. The business logic and API connections will be handled later.

**Comment by davidwaititu** [comment]
Received
